- name: Install MariaDB
  ansible.builtin.apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-mysqldb
    state: present
    update_cache: yes

- name: Start and enable mysql
  ansible.builtin.service: 
    name: mysql
    state: started
    enabled: true

- name: Create mysql databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    login_user: "root"
  with_items: "{{ mariadb_databases }}"

- name: Create mysql users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: '{{ item.privileges | default( item.name + ".*:ALL,GRANT") }}'
    append_privs: "{{ item.append_privileges | default('no') }}"
    login_user: "root"
  with_items: "{{ mariadb_users }}"
